### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by kolabelmont** [Bilal-S/iis2tomcat#100]
i've seen this in the past but it was never addressed from what i can see.

No connection could be made because the target machine actively refused it 127.0.0.1:8009    at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   at BonCodeIIS.BonCodeCallHandler.ProcessRequest(HttpContext context)

i have identical setup on another machine which works. could you please recommend any solution? 

thanks!

**Comment by Bilal-S** [comment]
Sure thing.
The message that you see there is coming from the Windows.TCPIP library. We are surfacing it in the connector as FYI. 
So what the TCP/IP library is telling us in this context is that when we made a connection attempt on port 8009 the host machine (Tomcat) refused the connection. 
To check this you can use PowerShell and see whether you can connect to your Tomcat instance on port 8009 on the machine.

The PowerShell command is
`Test-NetConnection -ComputerName <address> -Port <port>`

Thus
`Test-NetConnection -ComputerName 127.0.0.1 -Port 8009`

Reasons:
- Tomcat is not configured to accept AJP traffic on 8009 (this is the new default)
- Tomcat is down
- Tomcat connection limit has been reached etc.

**Comment by kolabelmont** [comment]
so it failed when i ran the powershell commend. not sure why it can't connect to port 8009. any ideas? tomcat was defaulted to use that port and in the server.xml i see that's the case.

**Comment by kolabelmont** [comment]
looks like for some reason port 8009 is not listening. any idea why?

**Comment by kolabelmont** [comment]
figured it out. was a problem with the config files. thanks for your help.

**Comment by Bilal-S** [comment]
Glad to hear you worked it out.
