### ISSUE TITLE
Object Moved Page When Using <cflocation> to CAS Login Page

### ISSUE THREAD

**Issue by thelarin** [Bilal-S/iis2tomcat#103]
We are moving away from Adobe CF to Lucee. I have a Windows 2019 test server with Lucee 5.3.6.68/Tomcat 9.0.35/BonCodeAJP Connector Version 1.0.41.

The security in one of our CF applications sends users to CAS for login purposes. We use the "cflocation" tag to perform this. When we hit the app main page, IIS is returning a page that simply says "Object Moved". When I look at the browser response headers, I see the correct Location URL in the Response Header. However, the HTTP status code is 200. Shouldn't it be a 302?

If I manually log in first by going to our CAS login page, our app works properly.

If I change our setup to simply use Tomcat instead of IIS, the app sends users to the CAS login page first as expected.

Erick

**Comment by thelarin** [comment]
Ok, I figured out the issue. When I initially had everything set up, the "cflocation" to our CAS login page was working. Then as I was debugging our app, IIS kept returning the generic 500 Internal Server Error page. I found that I could set the BonCode "EnableHTTPStatusCode" variable from True to False which showed me the CF debugging information I needed.

So my question is, how can I keep the redirects working AND be able to see CF debugging information coming from Lucee?

**Comment by Bilal-S** [comment]
This may have to be done as a feature addition to see whether we can transfer HTML output in addition to status code to IIS.
The current alternative is to capture CFML errors and save them via a onError in your Application.cfc

**Comment by thelarin** [comment]
Thanks for the quick reply Bilal. We do capture and store the errors already. I was looking for a way to easily show them to our app developers. The errors appear as expected when going to the localhost URL on the server itself.

In the meantime, I discovered that I can uncheck the "Status code" box in Lucee under Settings > Error. I can do this for our test/development instances only which is where our developers will benefit the most.

**Comment by Bilal-S** [comment]
closing for now.
