### ISSUE TITLE
Could not load type 'BonCodeIIS.BonCodeCallHandler'. 

### ISSUE THREAD

**Issue by krishpai** [Bilal-S/iis2tomcat#104]
Hello,

I deployed BonCode connector on IIS 8.5 as guided by the user guide and configured connection to Tomcat9. 
When I tried to launch a .jsp page under an application under Default Web Site I get the error

**Could not load type 'BonCodeIIS.BonCodeCallHandler'.** 

----------------------------------------------------------------------------------------------------------------------------------
Server Error in '/CustomerServiceApplication' Application.
Could not load type 'BonCodeIIS.BonCodeCallHandler'. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.Web.HttpException: Could not load type 'BonCodeIIS.BonCodeCallHandler'.

Source Error: 

 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.   

Stack Trace: 
[HttpException (0x80004005): Could not load type 'BonCodeIIS.BonCodeCallHandler'.]
   System.Web.Compilation.BuildManager.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) +10038490
   System.Web.Configuration.HandlerFactoryCache.GetTypeWithAssert(String type) +40
   System.Web.Configuration.HandlerFactoryCache.GetHandlerType(String type) +14
   System.Web.Configuration.HandlerFactoryCache..ctor(String type) +22
   System.Web.HttpApplication.GetFactory(String type) +89
   System.Web.MaterializeHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +266
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +50
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4261.0

------------------------------------------------------------------------------------------------------------------------------------
Any idea what could be missing here?

Thanks
Krish

**Comment by Bilal-S** [comment]
Krish:
there could be a handfull issues at plat.
Most likely one would be that there is no `/BIN` directory and/or the main  `.dll` files are not in the `BIN` directory.

You can simply try to use the installer to do all the steps for you and check.
Make sure you use a site-specific install, select the site you wish to use and `jsp` as processing type.

**Comment by Bilal-S** [comment]
closing issue.
