### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by RFBennet** [Bilal-S/iis2tomcat#107]
It looks like maybe 1.0.42 might need a slight adjustment. With it installed, if I navigate to https://_my-web-app-site_/a.jsp?BonCodeConnectorVersion=true I get:

**BonCodeAJP Connector Version 1.0.41
using setting file in C:\WINDOWS\BonCodeAJP13.settings**

Where I'd expect it to say version 1.0.4.2 instead of 1.0.41.

Also, it appears to be listed as version "1.0" within _Programs and Features_ on Windows. I'm not sure if that's by design or not.

Is this something that can be looked into and/or updated, or is there a different way in which we should detect current installations?

**Comment by Bilal-S** [comment]
Thanks for noting this.
Will correct with next release.
