### ISSUE TITLE
AJP request with invalid prefix (18)

### ISSUE THREAD

**Issue by PaoloBiondi** [Bilal-S/iis2tomcat#108]
Hello,
my Coldfusion server has the following setup: IIS -> boncode 1.3 -> undertow, Undertow is bundled with Commandbox from Ortus solutions.
I have an issue with requests that randomly fail with a "502 Bad Gateway" error from IIS, from what I see they don't get past the connector as they are not tracked by FusionReactor.

In undertow console output I find many entries like this:
[ERROR] io.undertow.request: UT005011: Ignoring AJP request with prefix 18

Some additional details are provided in the topic I started on CommandBox forum:
https://community.ortussolutions.com/t/boncode-commandbox-ajp-connection-error/9103/4

Is there anything else I can test or check?

**Comment by Bilal-S** [comment]
@PaoloBiondi 
I read through the command box feedback. If you are not using `EnableAdobeMode` can you provide some log info?
Ideally a packet capture from Wireshark but also an exchange from BonCode for the requests that show this error?
You can use the `LogIPFilter` setting to get logs only for one IP.
See setting documentation:
http://www.boncode.net/connector/webdocs/Tomcat_Connector.htm#_Toc38268635

Also your current settings file would be helpful. Check  active setting file like so on localhost/server:
http://localhost/a.cfm?BonCodeConfigList=true
You can sent to my gmail (see documentation).

**Comment by Bilal-S** [comment]
Response via email sent.

**Comment by PaoloBiondi** [comment]
Hello Bilal,
thank you for your email, after a few weeks of testing I see that the number of errors dropped.

It looks like the problem was solved disabling the connection pool, setting MaxConnections to 0 in Boncode configuration file.

It’s not the optimal solution but at the moment I have no more time to play with it.
