### ISSUE TITLE
Fresh install -testing examples - no connection

### ISSUE THREAD

**Issue by alscheuring** [Bilal-S/iis2tomcat#109]
Hello,
I've been trying to get this to work all day with an existing server and have now tried with a fresh server. Hopefully you can point me towards a solution.

I have a fresh install of Windows 2016 with IIS 10.
http://localhost (shows IIS page)
http://localhost:8080/examples (shows tomcat examples page)

Installed the latest version of Boncode connector. All defaults.
Created an 'examples' folder in IIS's wwwroot.

In IIS admin, selected 'examples' folder and set verified it had the Boncode handler mappings.

http://localhost/examples (nothing happens. Just churns and churns and doesn't seem to ever timeout).

Notes:
With fresh install of Tomcat9, I uncommented the section that opens up port 8009.

Any ideas?

**Comment by alscheuring** [comment]
Figured it out. Tomcat 9 needs to be tweaked a little in server.xml for things to work correctly. 
<Connector port="8009" protocol="AJP/1.3" redirectPort="8443" secretRequired="false" />

**Comment by Bilal-S** [comment]
Glad you figured it.
Cheers,
Bilal

**Comment by TubeTime77** [comment]
> Figured it out. Tomcat 9 needs to be tweaked a little in server.xml for things to work correctly.

I'm running into the same issue. Like you, I "uncommented the AJP Connector port 8009" but have the same experience you describe. Can you tell me the tweaks made to the server.xml to correct the problem?

Many thanks,
Jason
