### ISSUE TITLE
Copy of #109 - Fresh install, no connection - BonCode Version 1.0.44 #help wanted

### ISSUE THREAD

**Issue by TubeTime77** [Bilal-S/iis2tomcat#111]
I've been using BonCode to connect IIS/Tomcat on a separate server for close to 10 years. I had successfully used the ISAPI redirector for some time at that point but the ease of the BonCode install, work it's done, without fail for that time, is much appreciated!

I just launched a new Windows 19 server, Tomcat 9, and JDK 11. All installs went well but just as #109 described. When attempting to launch examples through IIS the site appears to hang. No error message, and no connection. I'm hoping someone can provide me guidance on changes server.xml for Tomcat 9 might need.  I'm going to look at my Tomcat 7 setup to see what I can identify but hoping for any suggestions.

**Comment by Bilal-S** [comment]
Tomcat 9 has several changes. The most common one that stumps people is the default security settings of rejecting any request if the request secret is not present. Changes have to be made on both connector and tomcat sides.
-- please search "RequestSecret" in the manual

Also if you are remoting tomcat from Lucee or CF on different machines, make sure you have specified the  `address` attribute in server.xml for example `address="::1"` to allow connection from any source.

In both cases you will not get a response back correctly. You may only see a blank page or a connector reported error that connection has been refused.

If this is something else, please turn on connector logging and windows logging (see docs) and copy and paste logs or sent to my email (also in docs).

**Comment by TubeTime77** [comment]
Thank you, I will give this a try and refer to the manual for additional guidance on "RequestSecret". I will share my results here. I appreciate your response!

**Comment by TubeTime77** [comment]
This has resolved my issue. You can chalk it up as an "RTFM41 (read the f'in manual for once)".  I promise I did! A few adjustments and all is well. Thanks again!

**Comment by Bilal-S** [comment]
No worries. Glad you worked it out.
