### ISSUE TITLE
BonCode installed "for all sites" and Tomcat updates

### ISSUE THREAD

**Issue by watery** [Bilal-S/iis2tomcat#20]
I have the BonCode connector installed "for all sites" on a Windows Server machine hosting a single Tomcat instance.

When I update the Tomcat installation, is there anything to be done on the BonCode side or just replacing the Tomcat binaries will do it?

**Comment by Bilal-S** [comment]
Nothing changes for the connector if tomcat port and server stay the same.  

Bilal

**Comment by watery** [comment]
Great, thank you.
