### ISSUE TITLE
How can change the default root site to IIS

### ISSUE THREAD

**Issue by benzhuo** [Bilal-S/iis2tomcat#21]
Normally if entering 'http://localhost/' into the address bar, it will access to IIS default web page.  after installed the Boncode, it will access to the tomcat default web page.

could anyone can tell me how to change back to IIS default web page after installed the Boncode.
it is very important to me.

**Comment by Bilal-S** [comment]
For non-code related support please contact me on project host site (
tomcatiis.riaforge.org).
Add a new issue or click the contact project link.

Most likely scenario is that you have installed BonCode as wildcard handler
in IIS this will move all traffic to Tomcat. You can manage how handlers
are applied in IIS using the Handlers feature inside IIS manager (please
see IIS manual). Disable handler for the root directory of your site and,
then, select directories that need to handle via Tomcat again and enable
BonCode. If you do not need all traffic to flow to tomcat do not use a
wildcard handler, e.g. only process JSP than remove the wildcard and add a
JSP handler instead.

**Comment by benzhuo** [comment]
Hi Bilas,
    thank you for your comment.
    I have registered an account on the host site but  don't know why it is always failed when I logging in and I am sure I input the right username and password.
