### ISSUE TITLE
packages.config does not exist for BonCodeIIS

### ISSUE THREAD

**Issue by nicholas-brooks** [Bilal-S/iis2tomcat#23]
It is referenced in the BonCodeIIS.csproj but does not exist in the repository.

**Comment by Bilal-S** [comment]
Thanks for letting me know. 
I will update later today. 

Bilal

**Comment by Bilal-S** [comment]
Nicholas,
this file is in the repository. You can browse for it.
https://github.com/Bilal-S/iis2tomcat/blob/master/BonCodeIIS/BonCodeIIS.csproj

**Comment by Bilal-S** [comment]
I added the packages.config file as well. Thanks again for letting me know.
