### ISSUE TITLE
 iis2tomcat slow down the request  of  rest service  

### ISSUE THREAD

**Issue by geosmart** [Bilal-S/iis2tomcat#26]
1. When i request the rest service at port 8080,it response with 50ms to 100ms
2. But when i request the rest service at port 80,it response with 1300ms to 1500ms
In conclude,The port 80 solwer the 8080 port ,nearly 1000ms! 

I use the rest service in an online platform which ask the rest service have to be response with 1000ms.

Any help to make it response faster?  Thanks!

**Comment by Bilal-S** [comment]
In general REST vs non-rest should not make a difference. To investigate, please open a ticket on the riaforge site. When describing please include:
- your installation: Win version, Tomcat version, other IIS modules/features installed
- behavior for non REST calls
- using servlets? JSP? CFML, other setup?
