### ISSUE TITLE
ACF2016 error

### ISSUE THREAD

**Issue by davequested** [Bilal-S/iis2tomcat#28]
Hi Bilal

I've started using your connector, which has been working great, many thanks. For some requests though I'm seeing these errors. It's like ACF2016 has thrown an error but the connector/iis can't return it or something:

> Exception Details: 
> System.Web.HttpException: Request timed out.
> 
> Source Error: 
> An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
> 
> Stack Trace: 
> [HttpException (0x80004005): Request timed out.]

Any ideas?

Dave

**Comment by davequested** [comment]
I've dug further, it seems if I POST data from a form using  enctype="multipart/form-data" that it hangs for ages then returns this error.

**Comment by Bilal-S** [comment]
Can you post your active config?
http://localhost/a.cfm?BonCodeConfigList=true

Run this on server.

**Comment by davequested** [comment]
Hi Bilal

Here's my .settings file:

`<Settings>
<Server>localhost</Server>
<Port>8016</Port>
<EnableRemoteAdmin>False</EnableRemoteAdmin>
<EnableHeaderDataSupport>True</EnableHeaderDataSupport>
<AllowEmptyHeaders>True</AllowEmptyHeaders>
<EnableAdobeMode>True</EnableAdobeMode>
<EnableHTTPStatusCodes>True</EnableHTTPStatusCodes>
<ResolveRemoteAddrFrom>HTTP_X_FORWARDED_FOR</ResolveRemoteAddrFrom>
<LogLevel>1</LogLevel>
<LogDir>c:\temp</LogDir>
</Settings>`

I get this error in the logs:

`2016-09-25 14:16:49 BonCode AJP Connenctor version 1.0.29
2016-09-25 14:20:00 1.0.29 ERROR 
TCP Client level -- Server/Port:localhost/8016
Thread was being aborted.
   at BonCodeAJP13.BonCodeAJP13ServerConnection.ComunicateWithTomcat()
   at BonCodeAJP13.BonCodeAJP13ServerConnection.HandleConnection()
   at BonCodeAJP13.BonCodeAJP13ServerConnection.p_CreateConnection(BonCodeAJP13PacketCollection packetsToSend)`

**Comment by Bilal-S** [comment]
OK. Thanks for sharing. Will have to recreate somehow.
Are there any errors recorded in CF /Tomcat logs that you can find?

Also, can you help me create a test case.
Requirements: ACF 2016, Post a form with enctype="multipart/form-data", can we use a blank post-to-page? Does a file need to be posted?

Thanks,
Bilal

**Comment by davequested** [comment]
I've narrowed down the issue. If you create a test.cfm and put this code there:

```
<cfoutput>
    <form action="test.cfm?action=true" method="post" enctype="multipart/form-data">
        <button type="submit" name="submit">Submit</button>
    </form>
</cfoutput>

<cfif isDefined("url.action")>
    <cfdump var="#getHttpRequestData()#">
</cfif>

<cfabort>
```

It seems to hang when trying to getHttpRequestData() for a POST/multipart form submission

**Comment by Bilal-S** [comment]
Thanks Dave. 
That looks more like an Adobe specific behavior that I have to reverse engineer. Adobe adds their own spin to the protocol and behavior is not published.

**Comment by davequested** [comment]
Thanks for looking into this Bilal, appreciated. If it helps, using the WSCONFIG way that Adobe uses it works fine.

We want to use BonCode for performance, no horrible Jakarta folders everywhere and also that WSCONFIG doesn't work for all sites properly on ACF2016.

**Comment by Bilal-S** [comment]
No problem. Just going to take a bit longer to check out.

**Comment by davequested** [comment]
Thanks Bilal, if you need any more info just shout. Appreciate your efforts here.

**Comment by Bilal-S** [comment]
@davequested I did find and resolve this issue but I found something else with ACF2016 I need to investigate that is related. Will be a bit longer.

**Comment by davequested** [comment]
Fantastic Bilal, just give me a shout when you'd like me to test.

**Comment by Bilal-S** [comment]
Resolved. Please check [1.0.31](https://github.com/Bilal-S/iis2tomcat/releases/tag/1.0.31) release.

**Comment by davequested** [comment]
Thank you sooooo much Bilal. All working as expected now. Appreciate the fix.

**Comment by Bilal-S** [comment]
closing.
