### ISSUE TITLE
getPageContext().getRequest().getRequestURI() not passing full URI

### ISSUE THREAD

**Issue by davequested** [Bilal-S/iis2tomcat#29]
Hi Bilal

In ACF2016, we're using getPageContext().getRequest().getRequestURI() to get the full URI for a redirect, however it doesn't pass the full URL if SES vars appended.

If we call
`/somepath/somefile.cfm/var1/test`

The getRequestURI() returns:
`/somepath/somefile.cfm`

If we use the normal ACF Web Connector it does work as expected and return everything.

**Comment by Bilal-S** [comment]
See docs under cgi.path info:
Add:
`<PathInfoHeader>path-info</PathInfoHeader>`
in your setting file.
