### ISSUE TITLE
Boncode URL Phraseing/Issue

### ISSUE THREAD

**Issue by majianlord** [Bilal-S/iis2tomcat#30]
So I have found a issue and I am not sure how to handle it/make it work.   We are using Windows 2012 R2 IIS 8 and Boncode on the Front with Tomcat 8.0.35 on the back end.   We have a Vendor Product installed in tomcat and it uses rest api's to talk to itself.   If we use it in Tomcat it works just fine.  If we use it on the IIS side some of the rest calls Fail.

Working Example From Local Host call
"DELETE /rest/authhandlers/Facebook%20OAuth HTTP/1.1" 204 
Failing Example from IIS Boncode.
"DELETE /otdsws/rest/authhandlers/Facebook OAuth HTTP/1.1" 400 1033

As you can see,  What Tomcat is getting from Boncode is the name without the %20 character in the URL,   This is causing the rest services to throw an error "The request sent by the client was syntactically incorrect."

We have been using boncode for a number of years and love how it works and what it does but we have run into something that might force us back to using Jakarta Redirector (Shutter the thought of that..).   So as a Last ditch effort I thought I would post the issue here and see if anyone else has seen this issue before.

**Comment by Bilal-S** [comment]
@majianlord Thanks for the feedback. However, the connector does not directly change the URL. It passes things through as submitted. 

Unfortunately, IIS already decodes the URL before allowing lower level modules access to data. 
Here are a few questions on stackoverflow related to this behavior:

http://stackoverflow.com/questions/21413393/how-to-stop-iis-from-decoding-url

http://stackoverflow.com/questions/13095416/does-request-querystring-automatically-url-decode-a-string

The simplest way for you would probably be to enable double encoding to be passed, then you can write your URL as "DELETE /rest/authhandlers/Facebook%2520OAut"

You will need to enable it by changing the configuration/system.webServer/security/requestFiltering@allowDoubleEscaping setting in the applicationhost.config or web.confg file.

This is not recommended security practice and you should check the impact for your scenario.

HTH,
Bilal

**Comment by majianlord** [comment]
Is there anything we can do in the connector to re encode the URL in the boncode connector.  Could i add some setting to encode things being sent to Tomcat.  I dont mind digging though the code to try and add it myself but i am really at a loss as to what to do.

**Comment by majianlord** [comment]
Side note,   I cant change the Vendors Code for the post being sent to the Rest API so its why i was looking to work int he boncode side or iis urlrewrite or some such.

Thanks.

**Comment by Bilal-S** [comment]
Ok let me see what can be done.

**Comment by majianlord** [comment]
I think I have found a way to implement a work around,   UNENCODED_URL  According to IIS URL REWRITE the documentation found here.

https://www.iis.net/learn/extensions/url-rewrite-module/url-rewrite-module-configuration-reference#Preserving_Original_URL

The Server Variable "UNENCODED_URL" contains the original URL exactly as it was requested by a Web client, with all original encoding preserved.   If we had a way to tell Boncode to use that on its pass though to Tomcat instead of the Default that might solve the problem for me,  AKA Like a setting to use it turn off by default?

**Comment by majianlord** [comment]
Ok a little bit more info,  In digging into what Tomcat is getting,   I have the following listed as a header
header=X-SERVER-URL=/otdsws/rest/authhandlers/Google%20OAuth
This is the correct Encoded URL as it should be being passed on to Tomcat,   Might be as simple as Putting in something like you have for X-Forward-forward where we put a setting in that would translate this header that seems to be there by Default already instead of the URI that is being sent.

**Comment by Bilal-S** [comment]
We can look into this but it would be a security hole since it would allow the override of a server generated value by client. Anyone passing a value for this will change the URL that is called when this is enabled.

**Comment by majianlord** [comment]
It looks like I created the Custom Header with my IIS URL reWrite Rule and I didn't relize it. As Tomcat shows it without the HTTP in front of it.   This is the rule I put in place   
<rewrite>
            <rules>
                <rule name="HTTP_X_SERVER_URL">
                    <match url="(.*)" />
                    <serverVariables>
                        <set name="HTTP_X_SERVER_URL" value="{UNENCODED_URL}" />
                    </serverVariables>
                    <action type="None" logRewrittenUrl="true" />
                </rule>
            </rules>
        </rewrite>

**Comment by Bilal-S** [comment]
closing for now.
