### ISSUE TITLE
IIS Worker Process High CPU

### ISSUE THREAD

**Issue by davequested** [Bilal-S/iis2tomcat#31]
Hi Bilal

Just wondering if you're aware of any mis-configuration issues with IIS Worker Process going crazy (high CPU). We've just put into production and getting this happening every so often. It completely freezes everything and we have to restart IIS and ColdFusion 2016.

Dave

**Comment by davequested** [comment]
Googling I found this:
http://tomcatiis.riaforge.org/index.cfm?event=page.issue&issueid=71B7D72D-DD88-A819-2F4A66D0849E5C07

Sounds like we need to turn off Garbage Collection for .NET?

**Comment by davequested** [comment]
Our current boncode.settings:

```
<Settings>
<Server>localhost</Server>
<Port>8016</Port>
<PacketSize>65536</PacketSize>
<MaxConnections>1000</MaxConnections>
<EnableRemoteAdmin>False</EnableRemoteAdmin>
<EnableHeaderDataSupport>True</EnableHeaderDataSupport>
<EnableAggressiveGC>True</EnableAggressiveGC>
<AllowEmptyHeaders>True</AllowEmptyHeaders>
<EnableAdobeMode>True</EnableAdobeMode>
<EnableHTTPStatusCodes>True</EnableHTTPStatusCodes>
<ResolveRemoteAddrFrom>HTTP_X_FORWARDED_FOR</ResolveRemoteAddrFrom>
<LogLevel>0</LogLevel>
</Settings>
```

And our connector in server.xml:
`<Connector port="8016" protocol="AJP/1.3" redirectPort="8449" tomcatAuthentication="false" maxThreads="1000" connectionTimeout="60000" packetSize="65536"/>`

**Comment by davequested** [comment]
Using the latest version of BonCode.

**Comment by Bilal-S** [comment]
Whenever previously issues were reported with CPU another IIS process using the same application pool was consuming the CPU. Normally the connector should be very limited in its use of CPU.
The issue you are highlighting from riaforge was related to high memory use. The CPU stayed consistent. You can try the resolution to see if that is related. Please see troubleshooting guide, last item on how to resolve it:
http://boncode.net/connector/webdocs/Tomcat_Connector.htm#_Toc459890778

Your settings look ok from what I can tell. Is there anything else that you are running on the IIS side, e.g. URL rewrite?

**Comment by davequested** [comment]
Hi Bilal

Thanks for the quick response. We do use URLRewrite, but not had any issues on our previous installation without BonCode (ColdFusion9, wsconfig). 

It's only happened a few random times, if it happens again, is there an easy way to determine what has caused it? I'm not much of an IIS whiz I'm afraid.

Dave

**Comment by Bilal-S** [comment]
hmm..
I will need some sort of test case to trace it down. Is there a call that produces this consistently?
You can enable Windows event log tracing of connector like this:
http://www.boncode.net/connector/webdocs/Tomcat_Connector.htm#_Toc459890762

IIS tracing can be controlled like this:
https://technet.microsoft.com/en-us/library/cc725786(v=ws.10).aspx

**Comment by davequested** [comment]
Hi Bilal

We tracked this down. As you suggest it was another IIS process, and it was URL rewrite. We had a mis-configured our redirect which was causing an infinite loop.

Hopefully this helps someone else!

Dave

**Comment by Bilal-S** [comment]
Sure thing

**Comment by msp1kpj** [comment]
We are having a high CPU of the web worker also. We are noticing that when the Tomcat server stop responding or the load balacer drops a tomcat server the Worker process is climbing to 100% cpu. I need help to determine what process is causing this. I have process dumps of the worker at the time of the spike and this is what the diagnostic tools comes back with. I don't know how to narrow it down in IIS any further. Can you suggest other ways I can look at what might be causing the issue?

Just for more info our IIS 8.5 server and Tomcat 7 server are two different machines.

In w3wp (7).DMP GC is running in this process. The Thread that triggered the GC is 23

Thread 23 - System ID 11340
Entry point   ntdll!RtlUserThreadStart+34 
Create time   12/6/2016 10:26:01 AM 
Time spent in user mode   0 Days 00:02:58.390 
Time spent in kernel mode   0 Days 00:04:50.609 




This thread is not fully resolved and may or may not be a problem. Further analysis of these threads may be required.



.NET Call Stack



Function 
System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr, System.Web.RequestNotificationStatus ByRef) 
System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr, System.Web.RequestNotificationStatus ByRef) 
System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr, System.Web.RequestNotificationStatus ByRef) 
System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr, System.Web.RequestNotificationStatus ByRef) 


Full Call Stack



Function   Source 
ntdll!NtWaitForSingleObject+a    
KERNELBASE!WaitForSingleObjectEx+94    
clr!CLREventWaitHelper2+38    
clr!CLREventWaitHelper+1f    
clr!CLREventBase::WaitEx+70    
clr!SVR::gc_heap::wait_for_gc_done+57    
clr!SVR::GCHeap::GarbageCollectGeneration+1da    
clr!SVR::GCHeap::Alloc+21c    
clr!Alloc+60    
clr!JIT_NewArr1+4cf    
0x00007ff9`ebe6b286    
0x00007ff9`ebe6a6f5    
0x00007ff9`ebe6a276    
0x00007ff9`ebe6140f    
System_Web_ni+2f6271    
System_Web_ni+2bd495    
System_Web_ni+2dabaa    
System_Web_ni+2bd6a3    
System_Web_ni+2b75de    
System_Web_ni+2c0561    
System_Web_ni+2bff92    
System_Web_ni+a15ea1    
clr!UMThunkStub+6e    
webengine4!W3_MGD_HANDLER::ProcessNotification+78    
webengine4!W3_MGD_HANDLER::DoWork+34f    
webengine4!RequestDoWork+34e    
webengine4!CMgdEngHttpModule::OnExecuteRequestHandler+21    
iiscore!NOTIFICATION_CONTEXT::RequestDoWork+224    
iiscore!NOTIFICATION_CONTEXT::CallModulesInternal+198    
iiscore!NOTIFICATION_CONTEXT::CallModules+36    
iiscore!NOTIFICATION_MAIN::DoWork+4b4    
iiscore!W3_CONTEXT_BASE::IndicateCompletion+97    
webengine4!MgdIndicateCompletion+60    
System_Web_ni+3696cb    
System_Web_ni+2c074f    
System_Web_ni+2bff92    
System_Web_ni+a15ea1    
clr!UMThunkStub+6e    
webengine4!W3_MGD_HANDLER::ProcessNotification+78    
webengine4!W3_MGD_HANDLER::DoWork+34f    
webengine4!RequestDoWork+34e    
webengine4!CMgdEngHttpModule::OnAuthenticateRequest+1f    
iiscore!NOTIFICATION_CONTEXT::RequestDoWork+ea    
iiscore!NOTIFICATION_CONTEXT::CallModulesInternal+198    
iiscore!NOTIFICATION_CONTEXT::CallModules+36    
iiscore!NOTIFICATION_MAIN::DoWork+422    
iiscore!W3_CONTEXT_BASE::StartNotificationLoop+94    
iiscore!W3_CONTEXT::ExecuteRequest+297    
defdoc!W3_DEFAULT_DOC_HANDLER::DoWork+73d    
defdoc!RequestDoWork+20d    
defdoc!CIISHttpModule::OnExecuteRequestHandler+1a    
iiscore!NOTIFICATION_CONTEXT::RequestDoWork+224    
iiscore!NOTIFICATION_CONTEXT::CallModulesInternal+198    
iiscore!NOTIFICATION_CONTEXT::CallModules+36    
iiscore!NOTIFICATION_MAIN::DoWork+4b4    
iiscore!W3_CONTEXT_BASE::StartNotificationLoop+94    
iiscore!W3_CONTEXT::ExecuteRequest+297    
webengine4!W3_MGD_HANDLER::DoChildExecute+7c    
webengine4!W3_MGD_HANDLER::ProcessNotification+9c    
webengine4!W3_MGD_HANDLER::DoWork+34f    
webengine4!RequestDoWork+34e    
webengine4!CMgdEngHttpModule::OnExecuteRequestHandler+21    
iiscore!NOTIFICATION_CONTEXT::RequestDoWork+224    
iiscore!NOTIFICATION_CONTEXT::CallModulesInternal+198    
iiscore!NOTIFICATION_CONTEXT::CallModules+36    
iiscore!NOTIFICATION_MAIN::DoWork+4b4    
iiscore!W3_CONTEXT_BASE::IndicateCompletion+97    
webengine4!MgdIndicateCompletion+60    
System_Web_ni+3696cb    
System_Web_ni+2c074f    
System_Web_ni+2bff92    
System_Web_ni+a15ea1    
clr!UM2MThunk_WrapperHelper+43    
clr!UM2MThunk_Wrapper+5a    
clr!Thread::DoADCallBack+13c    
clr!UM2MDoADCallBack+91    
clr!UMThunkStub+26d    
webengine4!W3_MGD_HANDLER::ProcessNotification+78    
webengine4!ProcessNotificationCallback+42    
clr!UnManagedPerAppDomainTPCount::DispatchWorkItem+134    
clr!ThreadpoolMgr::ExecuteWorkRequest+64    
clr!ThreadpoolMgr::WorkerThreadStart+2b6    
clr!Thread::intermediateThreadProc+7d    
kernel32!BaseThreadInitThunk+22    
ntdll!RtlUserThreadStart+34
