### ISSUE TITLE
401-error

### ISSUE THREAD

**Issue by TfGamon** [Bilal-S/iis2tomcat#33]
Hi Bilal, 
I installed the Boncode Connector on a Windows Server 2012 (64 Bit). Everything worked easy and I got my apps redirected from Tomcat 8.5 (Port 8080) to IIS 8.5 (Port 80). As long as I access my apps locally on the server (url-example http://myServer/myApp) everything works smothly. But when I try this on a remote machine I get a "401-Authentification-Error" coming from the IIS. When I access this app directly through Tomcat on the same remote machine (http://myServer:8080/myApp) the app works as expected.

What can I do to get the connector work, when accessing the app from a remote computer, as it already works when accessing locally from the server? Some adjustment in the IIS?

thanks
Thomas

**Comment by Bilal-S** [comment]
The connector only acts as pipe. It does not make a distinction between local and remote. 
If you are receiving a 401 error you should consult with either Tomcat or IIS for how to resolve it.  
Here is a link to IIS and how to resolve common HTTP 401 errors:
https://support.microsoft.com/en-us/kb/907273
