### ISSUE TITLE
Dead link to YouTube videos

### ISSUE THREAD

**Issue by adaugherity** [Bilal-S/iis2tomcat#34]
In README.md (which is displayed on the front page of GitHub project):
> YouTube Videos: http://tomcatiis.riaforge.org/blog/index.cfm/2011/4/10/Youtube-Videos

That just redirects to the front page of tomcatiis.riaforge.org, which say the project has moved to boncode.net, riaforge is no longer maintained, etc.; that page also has this same YouTube link, which redirects back to itself!  I was able to view the original blog post via the WayBack machine (web.archive.org) and found the YouTube videos that way.

Perhaps the README should just point directly to the YouTube channel, e.g. https://www.youtube.com/user/boncode/videos?

**Comment by Bilal-S** [comment]
OK. Thanks I have updated the link. ;o)
