### ISSUE TITLE
BonCodeConnectorVersion=true -> BonCodeAJP Connector Version 1.0.32 for 1.0.33

### ISSUE THREAD

**Issue by ljack** [Bilal-S/iis2tomcat#36]
Donwloaded 1.0.33 release from https://github.com/Bilal-S/iis2tomcat/releases/download/1.0.33/AJP13_v1033.zip  but version check url ?BonCodeConnectorVersion=true  says 1.0.32.

**Comment by Bilal-S** [comment]
Thanks for letting me know. I will repost shortly.

**Comment by Bilal-S** [comment]
done.
