### ISSUE TITLE
Negative connection IDs

### ISSUE THREAD

**Issue by ljack** [Bilal-S/iis2tomcat#37]
I'm seeing negative connection IDs in Boncode logs. And I's wondering if it's ok?

New Connection 4 of 0 to tomcat: [::1]:8009 ID: -7 [T-16524]
New Connection 5 of 0 to tomcat: [::1]:8009 ID: -6 [T-17628]
New Connection 6 of 0 to tomcat: [::1]:8009 ID: -5 [T-8228]
New Connection 7 of 0 to tomcat: [::1]:8009 ID: -4 [T-16524]
New Connection 8 of 0 to tomcat: [::1]:8009 ID: -3 [T-17628]
New Connection 9 of 0 to tomcat: [::1]:8009 ID: -2 [T-13572]
New Connection 10 of 0 to tomcat: [::1]:8009 ID: -1 [T-8228]
New Connection 11 of 0 to tomcat: [::1]:8009 ID: 0 [T-16524]
New Connection 12 of 0 to tomcat: [::1]:8009 ID: 1 [T-13572]
New Connection 13 of 0 to tomcat: [::1]:8009 ID: 2 [T-8228]
New Connection 14 of 0 to tomcat: [::1]:8009 ID: 3 [T-16524]

**Comment by Bilal-S** [comment]
yes that can happen if we do not use a connection pool. We get into negative Ids. No impact on the programs workings.
