### ISSUE TITLE
Maybe Issue With <MaxConnections>

### ISSUE THREAD

**Issue by majianlord** [Bilal-S/iis2tomcat#38]
My understanding of this Feature is it will pool connections to tomcat,  AKA leave them open for the next Request and then close them at a later time if they are not used.    But what I am seeing in the logs is New Connection for every page refresh I do, and then it closing the connection right after the page is sent to the browser.  Am I miss understanding how this is supposed to be working?   I did update my fork to the newest code base today and deployed to test out the fix for connection pools.

2016-12-29 09:29:02 Closing Connection ID: 1 [T-8176]
2016-12-29 09:29:03 New Connection 1 of 500 to tomcat: XXXXXXXXX ID: 1 [T-12752]
2016-12-29 09:29:04 Closing Connection ID: 1 [T-4004]
2016-12-29 09:29:05 New Connection 1 of 500 to tomcat: XXXXXXXXX ID: 1 [T-12944]
2016-12-29 09:29:05 Closing Connection ID: 1 [T-8176]
2016-12-29 09:29:06 New Connection 1 of 500 to tomcat: XXXXXXXXX ID: 1 [T-7588]
2016-12-29 09:29:07 Closing Connection ID: 1 [T-8644]
2016-12-29 09:29:07 New Connection 1 of 500 to tomcat: XXXXXXXXX ID: 1 [T-10844]
2016-12-29 09:29:08 Closing Connection ID: 1 [T-8176]
2016-12-29 09:29:10 New Connection 1 of 500 to tomcat: XXXXXXXXX ID: 1 [T-14100]
2016-12-29 09:29:10 Closing Connection ID: 1 [T-10996]

**Comment by Bilal-S** [comment]
You are correct. 
If you set MaxConnections to a number larger than 5 it should create a connection pool. 
If not then it will open and close connections as needed. 
The default is not to use pools. 
Please see latest online docs on recommendations when you use pools.

**Comment by majianlord** [comment]
I am following the online docs from here,  http://boncode.net/connector/webdocs/Tomcat_Connector.htm#_Toc470191853

I have posted my Boncode Config and my Tomcat Connection String bellow but my reading for your docs say that it should be using connection polling but it seems to not be.  Maybe I am missing something or there is some new doc I need to look at.

    <Connector port="11906" URIEncoding="UTF-8" tomcatAuthentication="false" compression="off" packetSize="65536" connectionUploadTimeout="6000000" connectionTimeout="60000" protocol="AJP/1.3" redirectPort="8443" disableUploadTimeout="false" maxThreads="5000" />


<Settings>
<Server>XXXXXXX</Server>
<Port>XXXXXXX</Port>
<MaxConnections>500</MaxConnections>
<LogLevel>2</LogLevel>
<EnableRemoteAdmin>False</EnableRemoteAdmin>
<EnableHeaderDataSupport>False</EnableHeaderDataSupport>
<ForceSecureSession>False</ForceSecureSession>
<AllowEmptyHeaders>False</AllowEmptyHeaders>
<SkipIISCustomErrors>True</SkipIISCustomErrors>
<EnableAggressiveGC>False</EnableAggressiveGC>
<HeaderBlacklist>CERT_COOKIE,CERT_FLAGS,CERT_ISSUER,CERT_KEYSIZE,CERT_SECRETKEYSIZE,CERT_SECRETKEYSIZE,CERT_SERIALNUMBER,CERT_SERVER_ISSUER,CERT_SERVER_SUBJECT,CERT_SUBJECT,REMOTE_USER</HeaderBlacklist>
<PacketSize>65536</PacketSize>
<ResolveRemoteAddrFrom>HTTP_X_FORWARDED_FOR</ResolveRemoteAddrFrom>
<LogIPFilter>131.70.56.49</LogIPFilter>
</Settings>

**Comment by Bilal-S** [comment]
That looks about right.

If you use a connectionTimeout on the tomcat server.xml, please configure a corresponding timeout in IIS. 
See here:
http://boncode.net/connector/webdocs/Tomcat_Connector.htm#_Toc470191868

Can you validate that you have many connections without reuse:
Use something like netstat:
`netstat -an | find "8009" /c" `
or using a tool like TCPView:
https://technet.microsoft.com/en-us/sysinternals/tcpview

If you do not see many connections in TIME_WAIT status you are using a pool.

**Comment by Bilal-S** [comment]
Please let me know if there is an update to this. I will close in the next few days if no further feedback. We can reopen later if needed.

**Comment by Bilal-S** [comment]
closing
