### ISSUE TITLE
Sporadic 502 bad gateway errors

### ISSUE THREAD

**Issue by davequested** [Bilal-S/iis2tomcat#39]
Hi Bilal

We've had BonCode running for a few months now in production.

One thing we can't figure out is every so often we get a 502 Bad Gateway. It's impossible to replicate as if we hit the request again, it goes through fine.

Anything we should be checking? Things that worked for others?

Here's our boncode.settings:

```
<Settings>
<Server>localhost</Server>
<Port>8016</Port>
<PacketSize>65536</PacketSize>
<MaxConnections>0</MaxConnections>
<EnableRemoteAdmin>False</EnableRemoteAdmin>
<EnableHeaderDataSupport>True</EnableHeaderDataSupport>
<EnableAggressiveGC>True</EnableAggressiveGC>
<AllowEmptyHeaders>True</AllowEmptyHeaders>
<EnableAdobeMode>True</EnableAdobeMode>
<EnableHTTPStatusCodes>True</EnableHTTPStatusCodes>
<ResolveRemoteAddrFrom>HTTP_X_FORWARDED_FOR</ResolveRemoteAddrFrom>
<ReadTimeOut>3600000</ReadTimeOut>
<LogLevel>0</LogLevel>
<HeaderBlacklist>AUTHORIZATION,URL,SERVER_SOFTWARE,SERVER_NAME,SERVER_PROTOCOL</HeaderBlacklist>
</Settings>
```

And server.xml connector:

` <Connector port="8016" protocol="AJP/1.3" redirectPort="8449" tomcatAuthentication="false" connectionTimeout="121000" packetSize="65536"/>`

Thanks in advance

**Comment by Bilal-S** [comment]
Dave a certain number of 502 errors is expected to occur in any HTTP exchange. 
Whether something needs further investigation would very much depend on the nature of additional logs in the Windows Application Log. Do you have any samples of from those? 

Couple of things to look at:
EnableAggressiveGC ==> only needed if you are running in memory issues and you do not want to switch to WorkstationGC mode (more efficient). See manual how to do so.

ReadTimeOut ==> Why is this needed? I would normally rely on the IIS overall timeout. Set this to two mins using the IIS GUI:
![iisidletimeout](https://cloud.githubusercontent.com/assets/668901/21945335/b7aa50ba-d9a8-11e6-8e7c-d50336c72db7.PNG)

I am assuming you are running the latest version of the connector. If not please also consider upgrading.

Best,

**Comment by davequested** [comment]
Hi Bilal

I've turned off AggressiveGC, that seems to have calmed things down. IIS Worker Processes were going nuts, now they are bored!

Not yet seen a 502, but is early days.

Thanks for your input. Appreciated.

Dave

**Comment by Bilal-S** [comment]
closing for now.
