### ISSUE TITLE
Error: Setting blank AJP physical path: The specified path, file name, or both are too long. 

### ISSUE THREAD

**Issue by AndreyGritsik** [Bilal-S/iis2tomcat#41]
Hi Bilal.

I've configured Boncode AJP 1/3 connector ver. 1.033 using Windows 10 IIS and found in Windows log error from Boncode AJP 1/3 connector:  

> Setting blank AJP physical path: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
Is there any configuration in Boncode AJP 1/3 connector to change this limitation?

Thanks in advance.

**Comment by Bilal-S** [comment]
Not at the moment. The error is bubbled up from IIS map resolver.
However, this should only be used in context with Adobe Coldfusion implementations. If you are not using adobe CF you can ignore the warning.

**Comment by Bilal-S** [comment]
closing for now
