### ISSUE TITLE
Slow communication when using Boncode with Wildfly 10.1.Final

### ISSUE THREAD

**Issue by ljack** [Bilal-S/iis2tomcat#43]
Hi,
 We upgraded our system from JBoss 4.2.3 to Wildfly 10.1.Final. After the upgrade we noticed that communications through IIS->Boncode->Wildfly takes minimum of 1 seconds for every request. 
Even request for resources that don't exist. 
If we communicate directely to Wildfly (port 8080) the response time for on existing resource it 32ms. 

Wildfly has a large list of configurable parameters for network IO (https://docs.jboss.org/author/display/WFLY10/Undertow+subsystem+configuration).
  - Tried configuring PacketSize, no difference
  - Tried configuring Boncode to use connection pool but it always failed after a while. Must be some kind of configurational issue.

Any advice?

**Comment by Bilal-S** [comment]
I would have to look into this. Cannot see an obvious reason for the delay.

**Comment by Bilal-S** [comment]
Not getting the slowness.
Can you provide a little more detail on the environment. I used a standalone Windows server machine for everything.

**Comment by ljack** [comment]
Windows 6.3.9500 / Windows Server 2012 R2. IIS 8.5, IIS and WildFly both in the same machine.

BonCodeAJP13.settings:
```
<Settings>
	<Server>localhost</Server>
	<Port>8009</Port>
	<EnableRemoteAdmin>False</EnableRemoteAdmin>
	<EnableHeaderDataSupport>True</EnableHeaderDataSupport>
	<ForceSecureSession>False</ForceSecureSession>
	<AllowEmptyHeaders>True</AllowEmptyHeaders>
	<EnableHTTPStatusCodes>True</EnableHTTPStatusCodes>
	<MaxConnections>0</MaxConnections>
	<WriteTimeOut>2000</WriteTimeOut>
	<LogLevel>1</LogLevel>
	<PacketSize>16384</PacketSize>
	<LogDir>C:\inetpub\logs\LogFiles\BonCode</LogDir>
</Settings>
```

**Comment by ljack** [comment]
Ah, 
 It seems the slowdown was caused because we're using <Server>localhost</Server> and Wildfly was only listening ipv4 network. So this was the classical ipv6-ipv4 delay problem.
