### ISSUE TITLE
Problem with RecordSysEvent when Windows Event source is not registered

### ISSUE THREAD

**Issue by mvodopij** [Bilal-S/iis2tomcat#45]
I'm setting up the connector on IIS 10 (Windows 2016) and did manual install of the connector without registering Event source.

The connector will front Atlassian products (Bitbucket and Bamboo) which are installed on the same server.

I've noticed that Bitbucket likes to use colons inside URLs which will be blocked by .NET by default. I've worked around this by setting requestPathInvalidCharacters="" in httpRuntime.

After fixing .NET, connector started to give this exception:
```

Please check and adjust your setup:
Ensure that Tomcat is running on given host and port.
If this is a timeout error consider adjusting IIS timeout by changing executionTimeout attribute in web.config (see manual).
The source was not found, but some or all event logs could not be searched.  Inaccessible logs: Security.    at System.Diagnostics.EventLog.FindSourceRegistration(String source, String machineName, Boolean readOnly, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source, String machineName, Boolean wantToCreate)
   at System.Diagnostics.EventLog.SourceExists(String source)
   at BonCodeIIS.BonCodeCallHandler.RecordSysEvent(String message, EventLogEntryType eType)
   at BonCodeIIS.BonCodeCallHandler.ProcessRequest(HttpContext context)

```

Using remote debugger I've traced the origin of this error:
CallHandler.cs, line number 129:
```C#
//in some circumstances invalid path data can be supplied by client if so we will set the path to blank when exception occurs, e.g. http://project/group:master...master
try
{
    BonCodeAJP13Settings.BonCodeAjp13_PhysicalFilePath = context.Request.PhysicalPath;
}
catch (Exception exp)
{
    BonCodeAJP13Settings.BonCodeAjp13_PhysicalFilePath = "";
    RecordSysEvent("Setting blank AJP physical path: " + exp.Message, EventLogEntryType.Warning);
}

```

context.Request.PhysicalPath will raise an exception because of the colon inside URI. 

Looking at RecordSysEvent implementation it seems EventLog.SourceExists will raise an exception if it can't access certain Event logs (namely Security). I've modified implementation from:

```C#
//we only record events when event source exists
if (EventLog.SourceExists(sSource))
{
	//record in event log
	try
	{
		EventLog.WriteEntry(sSource, sEvent, eType, 417);
	} catch
	{
		//do nothing for now
	}

}
```

to:

```C#
//we only record events when event source exists
try
{
	if (EventLog.SourceExists(sSource))
	{
		//record in event log
		EventLog.WriteEntry(sSource, sEvent, eType, 417);
	}
} 
catch
{
	//do nothing for now
}
```

This solved my issue. 

Also consider removing a call RecordSysEvent from original exception handler for handling bad PhysicalPath. It seems using special characters in URI is common practice. If Event Souorce is registered it would fill Event log with lot's of messages while everything would work normally.

**Comment by Bilal-S** [comment]
Cool. 
Thanks for the feedback and suggestions.

**Comment by Bilal-S** [comment]
Implementation in 1.0.35.
Closing.
