### ISSUE TITLE
ajp13 install eorr  (runtime error at 98:2753) out of range

### ISSUE THREAD

**Issue by nilabaswo** [Bilal-S/iis2tomcat#49]
env desc:
my server is : windows 2008 R2 standard
iis application pool .net framework 4.0
tomcat verions is 7

**Comment by Bilal-S** [comment]
You can run install with a log option and post response.
`Connector_Setup.exe  /LOG`

Normally this would lead me to believ that there is something odd going on with your IIS installation. Is IIS installed and does it serve web-pages without errors?

**Comment by Bilal-S** [comment]
no response. closing for now.
