### ISSUE TITLE
Spool Error - Crashing IIS Worker Process

### ISSUE THREAD

**Issue by jwjung** [Bilal-S/iis2tomcat#50]
Been having an issue where a spool error is causing the IIS worker process to max out the CPU and hang.  Thanks in advance for you help.

ENVIRONMENT
----------------
Boncode Connector v1035 (but has been happening for the past few versions)
Windows Server 2012R2
IIS 8.5.9600.16384
Lucee 4.5/Tomcat

CONFIGURATION
------------------
Enabling FlushThresholdTicks reduced the frequency of these errors quite a bit from previous versions.  Before the event log was filled with spool errors, but would only occasionally crash.  Now, the error seems to guarantee a crash.

```
<Settings>
<Server>localhost</Server>
<Port>8009</Port>
<EnableRemoteAdmin>True</EnableRemoteAdmin>
<EnableHeaderDataSupport>True</EnableHeaderDataSupport>
<ForceSecureSession>False</ForceSecureSession>
<AllowEmptyHeaders>False</AllowEmptyHeaders>
<FlushThresholdTicks>50000</FlushThresholdTicks>
<PacketSize>65536</PacketSize>
</Settings>
```

WINDOWS EVENT LOG ERRORS
-----------------------------------
The windows event log shows the following errors when the worker process crashes (error details at end of this post):

[APPLICATION LOG]
Error during spool to client (browser may have navigated away): The remote host closed the connection. The error code is 0x800703E3. at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect) at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush() at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async) at BonCodeIIS.BonCodeCallHandler.PrintFlush(BonCodeAJP13PacketCollection flushCollection) 

[SYSTEM LOG]
A process serving application pool 'DefaultAppPool' suffered a fatal communication error with the Windows Process Activation Service. The process id was '5980'. The data field contains the error number.

WINDOWS EVENT LOG DETAIL
----------------------------------

[APPLICATION LOG DETAIL]

- EventData 
   Error during spool to client (browser may have navigated away): The remote host closed the connection. The error code is 0x800703E3. at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect) at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush() at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async) at BonCodeIIS.BonCodeCallHandler.PrintFlush(BonCodeAJP13PacketCollection flushCollection) 

+ System 
  - Provider 
   [ Name]  Microsoft-Windows-WAS 
   [ Guid]  {524B5D04-133C-4A62-8362-64E8EDB9CE40} 
   [ EventSourceName]  WAS 
 
  - EventID 5011 
   [ Qualifiers]  32768 
   Version 0 
   Level 3 
   Task 0 
   Opcode 0 
   Keywords 0x80000000000000 
 
  - TimeCreated 
   [ SystemTime]  2017-04-21T14:25:32.000000000Z 
   EventRecordID 352534 
   Correlation 

  - Execution 
   [ ProcessID]  0 
   [ ThreadID]  0 
   Channel System 
   Security 

- EventData 
  AppPoolID DefaultAppPool 
  ProcessID 5980 
   6D000780 

Binary data:

In Words
0000: 8007006D    

In Bytes
0000: 6D 00 07 80

======================

[SYSTEM LOG DETAIL]
- System 
  - Provider 
   [ Name]  Microsoft-Windows-WAS 
   [ Guid]  {524B5D04-133C-4A62-8362-64E8EDB9CE40} 
   [ EventSourceName]  WAS 
 
  - EventID 5011 
   [ Qualifiers]  32768 
   Version 0 
   Level 3 
   Task 0 
   Opcode 0 
   Keywords 0x80000000000000 
 
  - TimeCreated 
   [ SystemTime]  2017-04-21T14:25:32.000000000Z 
   EventRecordID 352534 
   Correlation 
 
  - Execution 
   [ ProcessID]  0 
   [ ThreadID]  0 
   Channel System 
   Security 

- EventData 
  AppPoolID DefaultAppPool 
  ProcessID 5980 
   6D000780 

Binary data:

In Words
0000: 8007006D    

In Bytes
0000: 6D 00 07 80

**Comment by Bilal-S** [comment]
@jwjung can you apply version 1.0.36 https://github.com/Bilal-S/iis2tomcat/releases/tag/1.0.36B an let me know what the difference if any is with the messages?

**Comment by jwjung** [comment]
@Bilal-S - I'll install it tonight, but it may be a few days before any events are logged.  I'll reply either way.

Thanks for your quick response and support.

**Comment by jwjung** [comment]
@Bilal-S - w/ version 1.0.36B, still seeing the Spool error on occasion in the application log (not really an issue), but no longer seeing the WAS 'fatal communication' error in the system log that wouold always hang the worker process.  I'll continue to monitor and let you know if anything changes.  Thanks.  ~JW

**Comment by Bilal-S** [comment]
Ok. Some spool errors are normal as part of TCP/IP communication process.
We will observe and close the issue in a few days.

**Comment by Bilal-S** [comment]
closing.
