### ISSUE TITLE
iis2tomcat: java.net.URISyntaxException

### ISSUE THREAD

**Issue by Shakal6969** [Bilal-S/iis2tomcat#53]
Hi,
As I'm currently planning an upgrade of Confluence Wiki from 5.8 to 6.2, I wanted to try out your connector. After having updated the content, I have issues with some images, resulting in an error 500:
```
java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in path at index 46: /download/attachments/127205566/image2017-5-22 12:37:59.png
    at com.github.kristofa.brave.servlet.ServletHttpServerRequest.getUri(ServletHttpServerRequest.java:27)
```
It's working fine when retrieving the image directly or via the old ISAPI filter. Seems that the URL is not passed as proper UTF-8? The ':' in the filename has been added by Confluence when pasting images from clipboard under version 5.8.

Regards
Nicolas

**Comment by Bilal-S** [comment]
The URL is passed as presented by client to IIS. The connector only sends UTF-8. In general colons are reserved characters, see (https://tools.ietf.org/html/rfc3986).  
It does not look like you are using the colons for its reserved purpose, so I would suggest the use of URL safe names for your image files such as `image2017-5-22-H-12-37-59.png`

You can ensure you use UTF-8 encoding on tomcat side by adding that directive to AJP protocol line in server.xml:
`URIEncoding="UTF-8"`
`<Connector protocol="AJP/1.3" port="8009" URIEncoding="UTF-8" ... />`

If the ISAPI connector works better, there is no need to change it.
The error is not thrown by the processing code on Tomcat, you could insert an alternative method to handle this format in `ServletHttpServerRequest.getUri()`

**Comment by Shakal6969** [comment]
I'm talking about IIS as proxy to my Confluence Wiki instance, I cannot define how file names are defined (the application does it!), and I cannot link directly to the files, as they are served by the application. The URIEncoding property is set to UTF-8 by default. 
Yes you're right, the ISAPI connector is definitely the better choice.

**Comment by Bilal-S** [comment]
Understood and agreed. Legacy apps that are not RFC compliant will have difficulty especially those that are proprietary and cannot be adjusted.
