### ISSUE TITLE
IIS to in-process tomcat

### ISSUE THREAD

**Issue by gan123** [Bilal-S/iis2tomcat#54]
Hi,
Is Boncode connector designed to work with bridging requests between IIS and a in-process tomcat? Or does it need to have tomcat installed on the machine and have to be routed through it?

Cheers.
Ganesh

**Comment by Bilal-S** [comment]
Ganesh:
Tomcat runs out of process. You can install it anywhere on any OS.  Most people will install on same machine for ease of use. 

During setup of connector you will point to the installation you wish to connect to.

**Comment by gan123** [comment]
Hi Bilal,
What I meant is we run a java process on a windows box using an embedded tomcat server. So essentially we don't need a tomcat installation on the box. Will this setup work? If yes then how?

Cheers!
Ganesh

**Comment by Bilal-S** [comment]
It does not matter how tomcat runs or what OS. 
Expose the AJP port and ensure you can connect to it. 
See docs.
