### ISSUE TITLE
Large header value causes a "Generic Connector Communication Error"

### ISSUE THREAD

**Issue by aeos** [Bilal-S/iis2tomcat#55]
When I add a request header that contains 6994 characters (may work with less) I receive a generic communication error if I set logging to level 1 I see:

2017-07-05 13:27:54 BonCode AJP Connenctor version 1.0.25
2017-07-05 13:27:54 1.0.25 ERROR 
TCP Client level -- Server/Port:localhost/8009
Value cannot be null.
Parameter name: buffer
2017-07-05 13:27:54 One Connection raised an error

**Comment by Bilal-S** [comment]
Please increase the package size from default 8Kb to another one, e.g. 32Kb
See docs on how to do this.

**Comment by aeos** [comment]
I tried that, and now I see the following in the lucee sterr:

05-Jul-2017 16:13:06.932 SEVERE [ajp-nio-8009-exec-8] org.apache.coyote.ajp.AjpMessage.processHeader Invalid message received with signature 514

**Comment by aeos** [comment]
Sorry I found a stackoverflow which indicates both sides need to be updated at the same time. resolved.

**Comment by Bilal-S** [comment]
Glad you were able to resolve this.
