### ISSUE TITLE
StackOverflowError with cfinclude and new HTTP()

### ISSUE THREAD

**Issue by cod-y** [Bilal-S/iis2tomcat#56]
We're having an issue with the BonCode connector. For some reason we can't narrow down, some requests seem to get caught in some kind of infinite loop and result in a StackOverflowError exception. These requests work without issue on the ISAPI connector. The simplest test case I can come up with is the below.

`<cfscript>
new HTTP();
</cfscript>`

I'm not 100% sure if this is related to the cfinclude issue I'm having. The site having issues with cfinclude is a pretty simple fusebox app that also fails with BonCode connector. The pattern seems the same in the sense that it gets caught in a loop and eventually ends in a StackOverflowError exception. If you would like, I can open a separate issue for that.

We're using ColdFusion 2016 update 4, Windows Server 2016, and we've reproduced this issue with 1.0.36 and 1.0.27.
[error_details.txt](https://github.com/Bilal-S/iis2tomcat/files/1265401/error_details.txt)
[cfinclude_error_details.txt](https://github.com/Bilal-S/iis2tomcat/files/1265402/cfinclude_error_details.txt)

**Comment by cod-y** [comment]
I enabled AdobeMode, and that seems to have done the trick. It's unclear _why_, but at least it's working. I wouldn't mind if someone could shed some light on the issue.

**Comment by Bilal-S** [comment]
Glad to hear you resolved it. 

Adobe uses non-standard extensions to the AJP protocol.

This is implement poorly and in a breaking fashion. Those two modes cannot coexist. 

I was certain that this is mentioned in documentation. I will check.
