### ISSUE TITLE
Server connection not being closed when client disconnects

### ISSUE THREAD

**Issue by Shepard** [Bilal-S/iis2tomcat#57]
I have a problem with Tomcat never getting notified about a client closing the connection.

This is especially noticeable in my setup because I have long-running connections (for Server Sent Events) which are supposed to stay open until the client closes the connection. The server keeps the connection alive and sends chunked data every now and then.

This happens both with connection pooling (MaxConnections > 0) and without.
I tried this with various versions and narrowed it down to 1.0.33. Before that it worked fine, beginning with this version it breaks.

Another symptom is that when I try to stop the application pool of my site in the IIS manager, the process gets stuck and doesn't shut down for a long time. In the task manager I can see a w3wp.exe process lingering around. When I set the application pool to use multiple worker processes (setting "Maximum Worker Processes" in the application pool's advanced settings) I have multiple w3wp.exe processes and when trying to stop the application pool in the IIS manager some of them stop but the one for the client I closed doesn't stop.
This behaviour doesn't happen in 1.0.32 either.

**Comment by Bilal-S** [comment]
Shepard:
thanks for the info. I will check and see whether something is obvious here.

**Comment by Bilal-S** [comment]
What is the behavior when you use 1.0.36 with setting of MaxConenctions = 0?

**Comment by Shepard** [comment]
I tried it with 1.0.36 and it showed the same behaviour as 1.0.33 with regard to this problem.

**Comment by Bilal-S** [comment]
Would mind sharing a few more data points?
What is the stack you are using (Railo, Lucee, JSP?)
What is AJP protocol line in your Tomcat `server.xml` look like (copy and paste)?
What is the Boncode Setting file look like (copy and paste)?
(of course remove anything that you feel uncomfortable sharing).
Thanks,
Bilal

**Comment by Shepard** [comment]
The stack is our own, a big codebase based on regular old servlets in Tomcat. For the servlet in question I implemented Server Sent Events using async servlets (I set "`asyncSupported = true`" on the servlet and then start an `javax.servlet.AsyncContext`). This allows me to keep the connection open and keep hold of it independently of the requesting thread so that at some later point every now and then another thread can push data to the HttpServletResponse and flush it (`response.flushBuffer()`).

The AJP protocol line in the server.xml is:

`<Connector port="1337" protocol="AJP/1.3" server="XYZ" redirectPort="443" tomcatAuthentication="false" packetSize="65536" maxThreads="1000" URIEncoding="UTF-8" />`

And the connector settings are:

`<Settings>
  <Port>1337</Port>
  <Server>localhost</Server>   
  <MaxConnections>0</MaxConnections>
  <FlushThresholdTicks>20000</FlushThresholdTicks>
  <EnableRemoteAdmin>False</EnableRemoteAdmin>
  <AllowEmptyHeaders>False</AllowEmptyHeaders>
  <PacketSize>65536</PacketSize>
  <LogLevel>0</LogLevel>
  <LogDir>c:\tmp</LogDir>
</Settings>`

**Comment by Shepard** [comment]
Hi Bilal,
I finally had a chance to test this and unfortunately I can still reproduce this problem. :-(
Maybe you can take another look at this.
Thanks!

**Comment by Bilal-S** [comment]
Thanks for checking Shepard.
What kind of notification are you expecting from client during disconnect? 
What is the timing? Browser navigates away to a different page or is closed?

Have you tried using a low idle timeout for both side?
for tomcat:
<Connector port="1337" protocol="AJP/1.3" redirectPort="8443" maxThreads="1000" connectionTimeout="**61000**" keepAliveTimeout="-1" packetSize="65536" />

For IIS use 1min applicaiton pool timeout?

Best,
Bilal

**Comment by Shepard** [comment]
Hi,

I run into this error with a load testing tool. So the client is a load testing script (I use Gatling) and I have it set so that it will create lots of connections to the web server (IIS), leaves them open for a while and then closes them. The application on the Tomcat side keeps the connections open so it can send events to them - until it receives a close from the client or gets a read error while trying to send data to the client. But IIS never tells Tomcat that the client closed the connection so it lingers around in Tomcat. We also don't seem to see any write errors in our application so it seems the connector accepts the data from the server side still even though it has nowhere to send it to because the client connection is gone.
When I run the same load test on v1.0.32 the connections between Tomcat and IIS get cleaned up fine.

I'm not sure if I've tried setting the application pool timeout. I will give this a go at some point and report back if it changes the situation in any way. Where would I set this in Tomcat?

Thanks,
Simon

**Comment by Bilal-S** [comment]
Thanks for clarifying.
The tomcat timeout is set in server.xml in the AJP protocol declaration. Set it slightly higher than IIS.  For example
`connectionTimeout="61000"`

HTTP is stateless. There is no specific end-of connection messaging needed AFAIK. A client does not need to let you know it went away. You can browse one site and in the middle of download switch to another site. Normally the webserver will respect the client directive in terms of connection, e.g. `keep alive`, but the client can do anything it likes.

If your goal is to clean up unused connections, a faster idle timeout is the best bet.

The BonCode connector is alive as long as the IIS connection is. Multiple IIS client connections can share a Tomcat connection if you use connection pooling, i.e. MaxConnection > 0. The lifespan is determined by IIS and client negotiations.

Hope this help,
Bilal

**Comment by Bilal-S** [comment]
ok.
I will check the code changes and see whether there is anything obvious.

**Comment by Bilal-S** [comment]
closing for now.
