### ISSUE TITLE
Sequence of NULs in AJP packet

### ISSUE THREAD

**Issue by Radiusz** [Bilal-S/iis2tomcat#58]
Hello Bilal

I have a problem with corrupted AJP packets. When setting the log level in the BonCode settings to 4 I can see that a sequence of more than 3k NULs interrupts the content of an AJP packet outgoing from Tomcat to IIS.

On several attempts when sending the same content I cannot reproduce this every time, but when the problem occurs it always interrupted the content at the same spot.

Inspecting the network traffic I noticed the following:
The TCP segments incoming on the web server do not contain these NUL-sequences. The corruption apparently only occurs when a AJP packet is divided between two TCP segments, but does not happen every time a AJP packet is split up in this way.

The sequence of NULs I can observe in the BonCode logs then appears after the part of the AJP packet contained in the first incoming TCP segment.

With AJP packet size set to 65536 in Tomcat and BonCode the remaining content of the so interrupted AJP packet was missing. The packet ended with NULs and though the next TCP segment contained the rest of this AJP packets content, the next packet logged by the BonCode connector only contained the content of the next packet out of this TCP segment.

After changing the AJP packet size to 8192 the corrupted AJP packet no longer ended with the NUL sequence. It then contained a part of the valid content, followed by a smaller number of NULs and then another part of the original content, cut of before its end.

This are the current BonCode settings:

```
<Settings>
  <Port>4223</Port>
  <Server>server.net</Server>   
  <MaxConnections>200</MaxConnections>
  <FlushThresholdTicks>20000</FlushThresholdTicks>
  <EnableRemoteAdmin>False</EnableRemoteAdmin>
  <AllowEmptyHeaders>False</AllowEmptyHeaders>
  <PacketSize>8192</PacketSize>
  <LogLevel>0</LogLevel>
  <LogDir>c:\logtmp</LogDir>
</Settings>
```

And this is the connector setting in the server.xml
```
    <Connector	port="4223" protocol="AJP/1.3" 
    			server="server"
    			redirectPort="6368" 
    			tomcatAuthentication="false"
               	maxThreads="200" 
               	 
               	packetSize="8192" 
               	URIEncoding="UTF-8"/>
```
    
I am using version 1.0.23, but could reproduce the same problem with 1.0.32 and 1.0.36.

Your help would be much appreciated.
Kind regards

**Comment by Bilal-S** [comment]
Thanks for showing this.
Do you have a small log file you can share? What log level are you using to see them?

**Comment by Radiusz** [comment]
Following an excerpt from the connector logs, with log level 4, while using packet size 65536. You can find the interrupting sequence of NULs in line 294:
[BonCodeAJP13Connection_Excerpt_20171110.log](https://github.com/Bilal-S/iis2tomcat/files/1488353/BonCodeAJP13Connection_Excerpt_20171110.log)

This is the payload of the corresponding TCP segment outgoing from the application server
[tcp_seg_appserver_2017-11-10.txt](https://github.com/Bilal-S/iis2tomcat/files/1488355/tcp_seg_appserver_2017-11-10.txt)

And this is the payload of the two TCP segments incoming on the web server
[tcp_seg_webserver_2017-11-10_0.txt](https://github.com/Bilal-S/iis2tomcat/files/1488357/tcp_seg_webserver_2017-11-10_0.txt)
[tcp_seg_webserver_2017-11-10_1.txt](https://github.com/Bilal-S/iis2tomcat/files/1488358/tcp_seg_webserver_2017-11-10_1.txt)

The NUL-sequence in the BonCode logs begins at the spot, the first TCP segment ends.

This is an excerpt of the BonCode logs, after having reduced the packet size to 8192. The NUL-sequence can be seen in line 267:
[BonCodeAJP13Connection_Excerpt_20171117.log](https://github.com/Bilal-S/iis2tomcat/files/1488370/BonCodeAJP13Connection_Excerpt_20171117.log)

Again the NULs are inserted at the spot corresponding to the end of the payload of the first TCP-segment incoming on the web server:

[tcp_seg_webserver_2017-11-17_0.txt](https://github.com/Bilal-S/iis2tomcat/files/1488374/tcp_seg_webserver_2017-11-17_0.txt)
[tcp_seg_webserver_2017-11-17_1.txt](https://github.com/Bilal-S/iis2tomcat/files/1488375/tcp_seg_webserver_2017-11-17_1.txt)

Thank you

**Comment by Bilal-S** [comment]
closing for now.
