### ISSUE TITLE
Two IIS sites sharing the same web root with two settings files

### ISSUE THREAD

**Issue by bdw429s** [Bilal-S/iis2tomcat#59]
I ran across an issue where I had a per-site installation of Boncode and I wanted two IIS sites sharing the same web root folder to proxy to two different back end AJP ports.  However, BonCode picked up the settings folder by convention based on the BIN folder in my web root so didn't have a way to have per-IIS-site settings that didn't involve a fie system convention.

1. Is that currently possible?
2. Could it be added if not?
3. You should consider joining up with the CFML Slack team. There's 2.3k+ people in there and it's a great way to  get quick help on anything CF-related.  https://cfml-slack.herokuapp.com/

**Comment by Bilal-S** [comment]
Brad,
Unfortunately, the file system is how IIS identifies and runs handler code that is site-specific. You can use virtual drive mappings or subapplications **(https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc772042(v=ws.10)** to add different directives to each site and still have same codebase. How difficult this is to achieve will depend on your current code organization.

## Using Virtual Directories

a) Create IIS sites pointing at different physical root paths, e.g. c:\sites\site1 and c:\sites\site2 etc., the BIN folders will be created under each site and you can add setting file accordingly.

b) Inside each site you can create a virtual drive and map to same code base: e.g. c:\sites\code 
Using lucee you may have to map the `code` path as well but you should be able to automate that using header information that is passed to along. See manual (http://www.boncode.net/connector/webdocs/Tomcat_Connector.htm#_Toc483166296) for this.

## Using sub  applications
You can achieve a similar outcome with a combination of virtual directories and sub application inside one IIS site. Inside your main site, create web-application as in above link. This will automatically create directories and assign BIN references. You can add the DLL files and Setting files manually, the installer will not copy them for you for sub-applications and manage the connections. For example
c:\mysite\customer1\BIN
c:\mysite\customer2\BIN
Inside each of sub applications, create virtual path to point to your code:
c:\mysite\customer1\code
c:\mysite\customer2\code
point to
c:\mysite\shared\code

## Can it be added
Indirectly yes. We would have to expand global mode and the setting file concepts. Then allow a mapping of IIS sites to Tomcat sites via a setting convention. Read this out and respond correctly to calls by directing traffic accordingly.

**Comment by bdw429s** [comment]
Hi @Bilal-S and thanks for the reply.  A couple of notes-- you mentioned Tomcat and Lucee, which are probably the most common use case for BonCode, but in my case I was actually using Adobe ColdFusion 2016 running on CommandBox.  Since Boncode is basically just an AJP proxy and AJP is a standard protocol, I was thinking you should probably remove most of the Tomcat references from Boncode since it's confusing when not actually using Tomcat as the servlet container.  That is, unless Boncode is actually tied somehow to Tomcat.  But it worked great with CommandBox (which runs JBoss Undertow).

So you answers make sense and I had thought about having a "fake" web root and using virtual directories to tie it all back together, but honestly that sounded pretty horrible from a management perspective.  This project was for a client and not at all how I would have set up IIS, but I was looking for something that would still allow them to keep their familiar IIS setup.  In the end, I convinced them to create a second web root for the parts of the site that they wanted to tie to a separate JVM (for scheduled tasks).

I think this could still be a useful feature for Boncode since peoples hard drives don't always match their IIS sites, plus people might not want to have the BIN folder littering their code as well.  It would be great to be able to specify the settings and DLL files without needing to rely on the file system even though that's the easiest and quickest way to get it running.

And finally, did you see my note about the CFML slack team?  I'm very serious about you getting on there.  Pretty much everyone active in the CF community are there and it's really great to be able to ping them there.  It would also be nicer to have this conversation on Slack too :)

**Comment by Bilal-S** [comment]
;o)

**Comment by carehart** [comment]
Hey, Brad, if this conversation had taken place on slack instead, how would someone observe it 6 months later, like I am doing here now? :-)

**Comment by bdw429s** [comment]
@carehart A slack conversation would never remove the need for a ticket of course, It's funny you posted that today as Bilal literally just joined the CFML Slack team this morning after months of me begging him to and it's already led to more progress in a single day than we've had in months on another issue I've been trying to work through with him.  Our findings will obviously be documented on the public ticket when were done but the back and forth troubleshooting progress has increased 20 fold! :)
