### ISSUE TITLE
SSO using Boncode

### ISSUE THREAD

**Issue by eduardoalda** [Bilal-S/iis2tomcat#61]
I'm getting authentication required when using IIS windows authentication (disabled all other Authentication methods in IIS, and only enabled Windows Authentication.) What should I configure in order to my domain credentials to pass-through?﻿

**Comment by Bilal-S** [comment]
Eduardo:
You are using the correct authentication method for Domain Authentication. My guess would be that you are logging in to the server with a local account while attempting to access the site or the server is not part of your domain.
This would be best troubleshot by your network admin.

Here is more background:
https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/authentication/windowsauthentication/

Overall, the connector is only a pass-through tunnel. It does not handle authentication or communicates with domain controllers directly.
