### ISSUE TITLE
Comunication error: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.

### ISSUE THREAD

**Issue by ecellini** [Bilal-S/iis2tomcat#70]
Hello Bilal,
on my ConnectionLog the are more of this error:

> 2018-07-23 14:33:50 1.0.37 ERROR 
> TCP Client level -- Server/Port:localhost/8010
> Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.
>    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
>    at BonCodeAJP13.BonCodeAJP13ServerConnection.ComunicateWithTomcat()
>    at BonCodeAJP13.BonCodeAJP13ServerConnection.HandleConnection()
>    at BonCodeAJP13.BonCodeAJP13ServerConnection.p_CreateConnection(BonCodeAJP13PacketCollection packetsToSend)

I use BonCodeAJP Connector Version 1.0.37, there is BonCodeAJP13.settings:
```
<Settings>
<Server>localhost</Server>
<Port>8010</Port>
<MaxConnections>500</MaxConnections>
<EnableRemoteAdmin>False</EnableRemoteAdmin>
<EnableHeaderDataSupport>True</EnableHeaderDataSupport>
<ForceSecureSession>False</ForceSecureSession>
<AllowEmptyHeaders>False</AllowEmptyHeaders>
<ResolveRemoteAddrFrom>HTTP_X_FORWARDED_FOR</ResolveRemoteAddrFrom>
<LogLevel>2</LogLevel>
<LogDir>C:\vhosts\XXXXXX\logConnector</LogDir>
<PacketSize>65536</PacketSize>
</Settings>
```

These is the server.xml of lucee 4:
`<Connector port="8010" protocol="AJP/1.3" redirectPort="8443" maxThreads="500" keepAliveTimeout="-1" connectionTimeout="60000" packetSize="65536" />`

With <MaxConnections>0</MaxConnections> i don't show any error.

can you help me to resolve this issue?

thank you

**Comment by Bilal-S** [comment]
@ecellini Was this also happening with 1.0.36 or is this something that started happening with 1.0.37?

**Comment by Bilal-S** [comment]
Also is your connection idle Timeout on IIS the same or lower then on Tomcat (60s). The IIS one should be slightly lower (1s). Try setting the tomcat connectionTimeout to 121000 and IIS Application Pool idle-timeout to 2 mins.

**Comment by ecellini** [comment]
Hello,
I have upgrade Connector from older version (date of file is October 04 2016), i have enable MaxConnections and the server it has become unstable.

The IIS Application Pool idle-timeout is 20 minutes and tomcat connectionTimeout="60000"

I will try new settings and check the logs.

thanks

**Comment by Bilal-S** [comment]
closing for now.
