### ISSUE TITLE
Lucee 4.5 with IIS7 on Windows2008R2: REST service

### ISSUE THREAD

**Issue by charlesr1971** [Bilal-S/iis2tomcat#73]
When I try and make a REST request. I get a 404 response. 

The REST Service is being correctly initialised, as it responds correctly via localhost:8888. 

My Boncode Handler is installed into IIS at a global level:

```
<add name="BonCode-Tomcat-Rest-Handler" path="/rest/*" verb="*" type="BonCodeIIS.BonCodeCallHandler, BonCodeIIS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=ad590a40d40745cf" modules="ManagedPipelineHandler" scriptProcessor="" resourceType="Unspecified" requireAccess="Script" allowPathInfo="false" preCondition="integratedMode" responseBufferLimit="4194304" />

```

**Comment by charlesr1971** [comment]
![img_0353](https://user-images.githubusercontent.com/827046/44060975-67ba6f64-9f4e-11e8-8324-e8454cc5fabd.JPG)

**Comment by charlesr1971** [comment]
The Lucee REST mapping is as follows:

```
<mapping default="false" physical="C:\domains\establishmindfulness.com\wwwroot\com\api\v1" virtual="/api.establishmindfulness"/>

```

**Comment by Bilal-S** [comment]
It looks like it already but please verify that your requests do not require a file or folder in your handler deceleration.
![mapping request restrictions](https://user-images.githubusercontent.com/668901/44088068-d2cbfa84-9f8f-11e8-854c-fe7f480af574.PNG)

If so this may be coming from Tomcat directly. Turn of `<EnableHTTPStatusCodes>False</EnableHTTPStatusCodes>` to see what tomcat is not liking.

**Comment by charlesr1971** [comment]
Hi Bilal. Thanks for the response. Yes. I have that panel unchecked. But I think it is set to 'File or Folder'. I have actually tried all 3 options, checked & unchecked. 

Do, I set <EnableHTTPStatusCodes> in web.xml?

**Comment by charlesr1971** [comment]
The weird thing is, that my other 3 Boncode Handlers work as expected for:

\*.cfc
\*.cfm
\*.cfml

**Comment by Bilal-S** [comment]
`EnableHTTPStatusCodes` is a BonCode setting. It needs to go to the BonCodeAJP13.settings file. For global installs the file is located in c:\windows (your system path)

As far as handler you can try `*.*` rather than `*` it seems to make a difference sometimes.

**Comment by Bilal-S** [comment]
closing
