### ISSUE TITLE
Default document

### ISSUE THREAD

**Issue by LeeJMan** [Bilal-S/iis2tomcat#77]
I’m trying the Boncode connector for the first time and I’m experiencing a problem where the default.cfm page is not recognized, even though it is properly configured within IIS.  It’s not recognizing and acting on the index.cfm page either, or any index pages.  It’s setup with Coldfusion on IIS.
Can you please advise on how to solve this?

**Comment by Bilal-S** [comment]
Are you using Adobe CF or any other flavor?
What did you do to install connector?

If adobe:
- did you follow the guide to remove Adobe hooks?
http://www.boncode.net/boncode-connector/using-boncode-with-adobe-coldfusion

If anyone other flavor:
- what flavor (bluedragon, railo, lucee?)
- how did you install?


The standard installer adds the default handler for .cfm and .cfc.
You can use IIS UI to do it manually if things are missing.
https://docs.microsoft.com/en-us/iis/configuration/system.webserver/handlers/

Adding default docs:
https://docs.microsoft.com/en-us/iis/configuration/system.webserver/defaultdocument/

**Comment by LeeJMan** [comment]
Thanks for the additional info Bilal, I did not try removing the Adobe hooks, I will try that.

I’m using Adobe Coldfusion.  The default handlers are added correctly for cfm and cfc

and pages work if I surf directly to them as /default.cfm for example.

 

Regards,

 

Lee
