### ISSUE TITLE
Fresh Ubuntu 18.04, JDK 1.11, Tomcat 9 - Lucee Install problem

### ISSUE THREAD

**Issue by derrickpeavy** [Bilal-S/iis2tomcat#78]
Bilal,

210 days ago (yes it was that long ago), I reached you on Twitter about installing Lucee on OS X 10.13.

Well,  I am working on upgrading my production server from Ubuntu 12 all the way to 18. Yep! And from Railo to Luccee.

I've been running CF servers since the late 90's and am migrating from Railo to Lucee. I've installed before on OS X Server, Ubuntu 10.04 and 12.04 and several OS X laptops. But I am still having problems with getting Lucee up. I think I might just have forgotten a step somewhere. 

So, I've set up a test instance at Digital Ocean and walked through all the installations I need (twice). I have a clean running Ubuntu 18.04 (LTS) with JDK 1.11, Tomcat 9, MySQL.

Tomcat is running, I can access Amin and Manager GUI.  Everything except Lucee looks good:

tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      980/mysqld          
tcp        0      0 0.0.0.0:1971            0.0.0.0:*               LISTEN      939/sshd            
tcp        0      0 10.10.0.5:53            0.0.0.0:*               LISTEN      878/named           
tcp        0      0 157.230.218.34:53       0.0.0.0:*               LISTEN      878/named           
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      878/named           
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      670/systemd-resolve 
tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      878/named           
tcp6       0      0 :::8009                 :::*                    LISTEN      2031/java           
tcp6       0      0 :::8080                 :::*                    LISTEN      2031/java           
tcp6       0      0 :::1971                 :::*                    LISTEN      939/sshd            
tcp6       0      0 :::53                   :::*                    LISTEN      878/named           
tcp6       0      0 ::1:953                 :::*                    LISTEN      878/named           
tcp6       0      0 127.0.0.1:8005          :::*                    LISTEN      2031/java 

I installed Lucee WAR at root of tomcat (/opt/tomcat/webapps).

Loaded up the page at http://bluebongos.net:8080/lucee/admin/admin.cfm and it's blank. 

Log from Lucee: 

"ERROR","http-nio-8080-exec-13","02/23/2019","21:48:52","",";Permission denied;lucee.runtime.exp.NativeException: Permission denied

What have I missed? I don't have any apps set in the Tomcat XML config yet because the Lucee install doesn't state that I need to. https://docs.lucee.org/guides/installing-lucee/osx/installing-tomcat-and-lucee-on-os-x-using-the-lucee-war-file.html

Can you help?

**Comment by derrickpeavy** [comment]
Apparently, the thing I appear to have forgotten is chmod +x *.sh on /opt/tomcat/bin

Because now, it's working!

**Comment by Bilal-S** [comment]
Derrick
I am glad you have been able to make it work. I am not sure about the 2min delay though. It should be faster than that.
I would recommend you post your question on the official lucee forum. There are quite a few people on there that can help: https://dev.lucee.org/

Best,
Bilal
