### ISSUE TITLE
Thread behavior difference between Windows Server 2008 and 2016

### ISSUE THREAD

**Issue by xouqoa** [Bilal-S/iis2tomcat#80]
We've been having an issue with our production servers where they randomly become unresponsive. I've been trying to help troubleshoot it with but I've come up with very little conclusive evidence for the cause.

The symptom is that a usage/request spike will come in on a server and the thread count (seen in Fusion Reactor) will spike. Usually it will not recover from this. IIS will still serve static pages, but any requests to cfml pages will hang and eventually get killed by IIS after a period of time. The only way to recover from this state is to restart the Lucee service.

On a hunch, we had our data center team set up a Windows 2008 server and we put it into load. The thread behavior (again, in Fusion Reactor) is completely different.

**Windows Server 2008 / Boncode 1.0.0.16 (pretty constant thread count)**

![image](https://user-images.githubusercontent.com/3315900/54945889-e01d7080-4f04-11e9-8034-9e51f45773ce.png)

**Windows Server 2016 / Boncode 1.0.0.41 (max thread count increases over time)**

![image](https://user-images.githubusercontent.com/3315900/54945917-f88d8b00-4f04-11e9-8c22-55fcffab35bf.png)

My theory is that when the thread count gets too high, and a large spike of requests comes in, Lucee goes kaput. What I'm not sure of is where the issue lives. I do know that we have two different production servers right now with full load running the same code, and we're seeing very different thread behavior which _seems_ strange at least.

The W2008 server currently only has 10 ajp-nio-8009-exec-x threads created, but the W2016 one(s) always have many more than that. 

I'm happy to provide more detailed information as far as versions and such, but I wasn't sure what would be useful. Both servers are running **Lucee 5.2.9.31**.

Any ideas?

**Comment by Bilal-S** [comment]
Jason:
In general the connection thread count should come down. The only reason should be that they remain  active for some reason. 
You can try to introduce a timeout for connections on Tomcat and IIs sides.

What configuration are you using on the connections? server.xml and BonCodeAJP13.settings (please remove modcfml security keys and IPs before posting).

A quick test is to set MaxConnection setting on BonCode to zero. This will force each connection to close. It has a little extra overhead, but you should be able to see a difference.

**Comment by xouqoa** [comment]
We have a few different versions of our set up right now in order to try and figure out what is going on, so I'll give a short description of the environment and then the relevant settings.

**Windows Server 2016 / Lucee 5.2.9.31 / Boncode 1.0.0.41**

There is no BonCodeAJP13.settings file present in c:\Lucee\AJP13 on these servers but I'm not sure why or if that is a problem. (We didn't notice this until I asked for the contents.)

[server.xml](https://www.dropbox.com/s/y1qh4r2ygrr9wgc/server.xml?dl=0)

**Windows Server 2016 / Lucee 5.2.9.31 / Boncode 1.0.0.16**

We tried an older version of Boncode (which was on the 2008 server) as a test, but connections were still stepping up. The server.xml file is the same as above, but it does have a BonCodeAJP13.settings file that looks like this:

`
<Settings>
  <Port>8009</Port>
  <Server>localhost</Server>   
  <MaxConnections>200</MaxConnections>
  <LogLevel>0</LogLevel>
  <LogDir>c:\temp</LogDir>
  <FlushThreshold>0</FlushThreshold>
  <EnableRemoteAdmin>False</EnableRemoteAdmin>
</Settings> 
`

**Comment by Bilal-S** [comment]
Jason:
The setting file for BonCoDe 1.0.16 seems off. It does not have a PacketSize deceleration and it would not match the non-default of 65536 size in `server.xml`.

Once you have tried `<MaxConnections>0</MaxConnections> ` we can look at other factors.

For example to have both IIS and Tomcat shutdown errand connections. You do this by setting
Application Pool Idle Timeout on the IIS side and `connectionTimeout` and `keepAliveTimeout` on Tomcat side.

Best,
Bilal

**Comment by xouqoa** [comment]
Hey Bilal,

Sorry, I completely forgot to follow up with you about this. (Busy, busy.. you know how it goes, I'm sure!)

We tried different versions of Boncode and didn't notice any improvement, so I think we've mostly eliminated it as a possible cause. We're still stable on Windows 2008, and I believe also on 2012. 

We are currently exploring FusionReactor as a potential culprit I believe.

**Comment by Bilal-S** [comment]
ok no problem.
closing for now.
