### ISSUE TITLE
Missing Packets?

### ISSUE THREAD

**Issue by advancedjgibson** [Bilal-S/iis2tomcat#85]
Hi Bilal,

First off, thanks for all you do!

We have upgraded our connector to v1041 and are noticing some odd issues.  In one particular issue, we are missing part of the page, as if the packets were dropped.  I've attached two files showing the logging from the connector.  The "bad" log renders a page that is missing about 4k of html from the the page, starting at line 300.  I've attached a .gif from WinMerge to demonstrate where this is happening.  The html missing is a chuck, it is not missing something like an include.  The text is cut in the middle of words, for example.  I hope this is clear, it's hard to describe.

Any ideas what might be going on?  Refreshing/Reloading the page, we'll get the full version about 60/70% of the time.  

Thank you! Jason
[_tomcat_good_response.txt](https://github.com/Bilal-S/iis2tomcat/files/3691464/_tomcat_good_response.txt)
[_tomcat_bad_response.txt](https://github.com/Bilal-S/iis2tomcat/files/3691469/_tomcat_bad_response.txt)
![_tomcat_html_missing](https://user-images.githubusercontent.com/19595747/66224335-a1caf000-e6a3-11e9-8984-7c538ea8907a.GIF)

**Comment by Bilal-S** [comment]
Should normally not happen in the middle of a transmission. Especially 30+% of the time.
What are your Tomcat/Boncode settings?

**Comment by advancedjgibson** [comment]
Please see below. Thank you!
Boncode:
<Settings>
	<Server>(IP address)</Server>
	<Port>8029</Port>
	<LogLevel>3</LogLevel>
	<LogDir>C:\logs\boncode</LogDir>
	<EnableRemoteAdmin>False</EnableRemoteAdmin>
	<EnableHeaderDataSupport>False</EnableHeaderDataSupport>
	<ForceSecureSession>False</ForceSecureSession>
	<AllowEmptyHeaders>False</AllowEmptyHeaders>
	<TomcatConnectErrorURL>/error.html</TomcatConnectErrorURL>
</Settings>

Tomcat:
  <Service name="Catalina">
    <Connector port="8082" protocol="HTTP/1.1" connectionTimeout="600000" redirectPort="443"/>
	<Connector port="8029" protocol="AJP/1.3" connectionTimeout="600000" maxThreads="1000" />
    <Engine name="Catalina" defaultHost="localhost">
      <Host name="localhost"  appBase="D:/inetpub/tomcatroot" unpackWARs="true" autoDeploy="true">
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="D:\mgmt\logs\tomcat" prefix="localhost_access_log." suffix=".txt" pattern="common" />
      </Host>
    </Engine>
  </Service>

**Comment by Bilal-S** [comment]
Ok thanks for the info.
I would recommend that you increase the packet size to accommodate the first package issue that sometimes can occur with AJP.

To do that for tomcat:
```
<Connector port="8029" protocol="AJP/1.3" connectionTimeout="600000" packetSize="65351"  maxThreads="1000" />
```

To do that for IIS:
add to BonCode Setting file:
```
<PacketSize>65351</PacketSize>
```

Other elements:
- Do you see anything in the error log for tomcat for this?

- If package size change does not help you we will need to check that the packages exist on the TCP layer through package capture (wireshark).

**Comment by advancedjgibson** [comment]
Thank you for your response!

There are no errors in Tomcat.

I'll adjust the settings for both, and try Wireshark if needed.

Thanks again!

**Comment by Bilal-S** [comment]
closing for now.
