### ISSUE TITLE
Server error in application '/'

### ISSUE THREAD

**Issue by genjav** [Bilal-S/iis2tomcat#87]
Hi

We install version 1.0.41.
And when the link is selected to enter the app, it shows the following error:

**Server error in application '/'

Could not load file or assembly 'BonCodeIIS, Version = 1.0.0.0, Culture = neutral, PublicKeyToken = ad590a40d40745cf' or one of its dependencies.
This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded**

It works using version 1.0.28 

We use:

IIS 7.5.7600.16385
Windows server 2008 R2 Standard 64 bits
Tomcat 9.0.12
Java 8 64 bits

Thanks

**Comment by Bilal-S** [comment]
genjav:
The BonCode connector has changed the needed minimum dot-net version. It is mention in the Release History but not clarified well in documentation. I will add it there.

`* Upd: Moved to minimum requirement of .net Framework 4.5`

You will need to have dot-net version 4.5 feature installed for BonCode version 1.0.37 onward to work.

**Comment by genjav** [comment]
Thanks for answering.

We install .net Framework 4.5 (and restart the server) and still display the same message.

Thanks again.

**Comment by Bilal-S** [comment]
Did you change the application pool on each of the sites to the correct version of .net framework as well or only install the framework?
Existing application pools do not get automatically changed.

**Comment by genjav** [comment]
Thank you for answering.
You were right. We change that property and now it works.

Thank you very much for your help.
