### ISSUE TITLE
White screen?  

### ISSUE THREAD

**Issue by shepherdblake** [Bilal-S/iis2tomcat#88]
We have been using the boncode connector for years on Windows Server 2008 R2 without issue.  We migrated our websites to Windows Server 2016 and now we are getting a sporadic white screen being returned to the browser.  Extensive troubleshooting has been performed on our side and we think the boncode connector is inserting some special characters in the request.  We've adjusted the settings file in every way imaginable without success.

We are proxying traffic to an Entrust SSM instance running on Tomcat.

We see that no updates have been made to boncode in quite some time.

Does this work properly on Windows Server 2016?  Are  you aware of any issues?

**Comment by Bilal-S** [comment]
All the known issues are in this github issue log. I add them here even if they arrive from different channels. 
So far no reports on sporadic white screens. Normally when there is a problem with the connector an HTTP error code should accompany the response even if the response is only a white screen.

AFAIK Windows 2016 does not have any special problems that distinguish it from others. 
Could you share the basic config, remove anything sensitive:

BonCode Config 
server.xml AJP protocol definition

Other question:
- when receiving `white screen` are you able to access tomcat, IIS?
- do you have any error logs enabled on Tomcat? On BonCode? => is there any error record?
- what do you believe is inserted by the connector into the HTML stream? A header? Payload?
- what are you processing on Tomcat: servlets, JSPs, cfml (flavor)?
- what version of Tomcat?


Best,
Bilal

**Comment by Bilal-S** [comment]
closing for now.
