### ISSUE TITLE
Handler "BonCode-Tomcat-WC-Handler" has a bad module "ManagedPipelineHandler" in its module list

### ISSUE THREAD

**Issue by mchampagne090719** [Bilal-S/iis2tomcat#89]
![image](https://user-images.githubusercontent.com/61837587/75992254-b404c080-5ec5-11ea-9536-fb71c40bd904.png)

**Comment by Bilal-S** [comment]
@mchampagne090719 
Have you reviewed the troubleshooting section of the manual for this. There are a few reasons:

http://www.boncode.net/connector/webdocs/Tomcat_Connector.htm#_Toc520189796

**Comment by Bilal-S** [comment]
closing for now.
