### ISSUE TITLE
* Add: Load Balancing Is this still on the map

### ISSUE THREAD

**Issue by majianlord** [Bilal-S/iis2tomcat#97]
Good morning,  We are running into an issue where we might have to go back to Jakarta as they want to be able to use more than 1 backend tomcat for a site and we don't have that ability with our Boncode connection,  Which we love a lot..

Hopeing to see if this is still planned for or was this kind of given up on..   Is there a Set of branches for 2.0 yet?

**Comment by Bilal-S** [comment]
@majianlord 
thanks for reaching out.

After we put load balancing on the road-map we did the analysis and it was hard to justfiy the effort.

A partial free solution already exists through use of Microsoft NLB and load balancing on AJP port. It covers the basic patterns and thus eliminated the majority of the use cases we were trying to implement.

You can also do functional load distribution if your app gives to that already by splitting each part of your site to go to a different tomcat instance. 

```
mysite.com/user -> go to tomcat A
mysite.com/shop -> go to tomcat B
mysite.com/api -> go to tomcat C
```

etc.

Hope this gives you more background.
Best,
Bilal

**Comment by Bilal-S** [comment]
@majianlord 
Thanks for sharing
