### ISSUE TITLE
Not-So-Silent Scripted Uninstall on Windows

### ISSUE THREAD

**Issue by RFBennet** [Bilal-S/iis2tomcat#98]
In Windows Server 2019, I'm able to get a scripted silent install to work successfully, but when attempting to configure a removal, I am unable to get it to be totally silent.

When using this command: `C:\Windows\unins000.exe /VERYSILENT /SUPPRESSMSGBOXES /LOG="C:\test\uninstall.log" /SP- /NORESTART`

I get a message box that stays on the screen until clicked:
                          ALL previous installations will be removed.
                          Do want to KEEP IIS features and roles created during install
                          (You can remove them later via IIS UI as well)?

Is there any way to remove/suppress this message box when doing a scripted removal, or can the InnoSetup installer be adjusted for future versions?

Thanks

**Comment by Bilal-S** [comment]
Will take me some time to rebuild and test.

**Comment by Bilal-S** [comment]
I have rebuild the installer and ran initial tests which looked good.
Can you let test and let me know if this works for you.
[AJP13_v1042.zip](https://github.com/Bilal-S/iis2tomcat/files/4903468/AJP13_v1042.zip)

**Comment by RFBennet** [comment]
I installed 1.0.42, and then ran the command in my first post, and it was silently uninstalled! Thanks!

**Comment by Bilal-S** [comment]
Thanks for confirming.
Closing.
