### ISSUE TITLE
Versions supported?

### ISSUE THREAD

**Issue by cmachemer-73** [Bilal-S/iis2tomcat#99]
I've been clicking around the documentation, and so far not found this bit of information, so I apologize if its out there, and I've just not stumbled upon it.  I was wondering if there's support for tomcat versions 8.5 or 9, or if this connector only works with versions 7 and 8.0?

**Comment by Bilal-S** [comment]
Yes Tomcat 8.5 & 9 are supported.

**Comment by cmachemer-73** [comment]
Interesting, OK.  I was able to upgrade from Tomcat 8.0.36 to Tomcat 8.0.53 with no problems.  But I've also tried an 8.5 version and a 9.0 version, and both have failed with an error saying it can't connect to the AJP connector on port 8009, which I did enable, and set the secretRequired variable to false.  Can you point me at some documentation that might help me figure out what I'm doing wrong?

**Comment by Bilal-S** [comment]
Yes.
Tomcat made changes that require you to setup differently and enabled a request secret requirement.
You need to define it on both sides of the connection.
Please see docs for `RequestSecret`

**Comment by Bilal-S** [comment]
I just see you set that.

**Comment by cmachemer-73** [comment]
Is it possible we're just using a version of the connector thats so old, that support for those versions wasn't there yet?  What i mean is, was some change necessary to add support for them at some point, or should any version of the connector support any of those versions of tomcat?On Jul 8, 2020 11:00 AM, Bilal Soylu <notifications@github.com> wrote:
I just see you set that.

**Comment by Bilal-S** [comment]
I did a complete fresh install with latest Apache 9 and BonCode 1.0.41 and everything worked for me without a problem.

This is what I used:
```
    <Connector protocol="AJP/1.3"
               address="::1"
               port="8009"
               redirectPort="8443" secretRequired="false" />
```

One thing to note is that the AJP connector in the `server.xml` file on Tomcat is now commented out by default. Have you removed the comment markers `<!-- -->`  around the AJP definition?

**Comment by Bilal-S** [comment]
Also a Tomat restart was required which I am assuming you already did.

**Comment by cmachemer-73** [comment]
Yes, that was uncommented, and the server restarted.  The one thing I don't yet have access to (I started with this company two days ago) is the IIS server where the connector lives.  I'm only working on the tomcat side of things thus far, which is on a different box.  Hopefully I can get that access tomorrow.

Might there be anything there that could help troubleshoot?  A log showing what the error might be?

-Chris

**Comment by Bilal-S** [comment]
Normally once you have the connector working it should continue regardless of Tomcat version (with exception of discussed security setting for Tomcat). 

If you get access to the IIS server  I would also recommend that you install the latest version of connector.

Logging:
You can turn on different levels of logging for the connector.  See general docs on Logging and `LogLevel` setting.
If it is protocol TCP/IP level problem you can also turn on Windows application logging for it which will capture some additional information.

Advanced Logging:
http://www.boncode.net/connector/webdocs/Tomcat_Connector.htm#_Toc38268638
